spring:
  application:
    name: Video English General Activities Service (VEGAS)

  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          profile:
            tenant-id: ${SSO_TENANT_ID}
          app-id-uri: ${VEGAS_SCOPE_URI}
          credential:
            client-id: ${VEGAS_APP_ID}
          base-uri: ${SSO_BASE_URI}
          user-flows: # is this really needed?, we're not signing directly into this service. This is a resource. Test removing this.
            sign-up-or-sign-in: ${SIGN_UP_OR_SIGN_IN_USER_FLOW_NAME:B2C_1_phone_based_sign_in_and_sign_up}
            
  datasource:
    url: ${VEGAS_DATABASE_URL}
    username: ${VEGAS_DATABASE_USERNAME}
    password: ${VEGAS_DATABASE_PASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

scheduledTasks:
  timeoutBookings: "0 * * * * *" #every 1 minutes

logging:
  level:
    org:
      springframework:
        security: DEBUG
        
zoom:
  clientConfig:
    accountId: ${ZOOM_ADMIN_ACCOUNT_ID}
    clientId: ${ZOOM_ADMIN_CLIENT_ID}
    clientSecret: ${ZOOM_ADMIN_CLIENT_SECRET}
