spring:
  application:
    profile: test

  cloud:
    azure:
      active-directory:
        b2c:
          enabled: true
          profile:
            tenant-id: ${SSO_TENANT_ID:a13a8498-c94f-4dac-9cb1-1cbb1e742758}
          app-id-uri: ${VEGAS_SCOPE_URI:https://wfeglobalb2cdev.onmicrosoft.com/vegas}         # If you are using v1.0 token, please configure app-id-uri for `aud` verification
          credential:
            client-id: ${VEGAS_APP_ID:dbf9e7a3-5dd9-4175-b246-0b5ec1bce543}           # If you are using v2.0 token, please configure client-id for `aud` verification
          base-uri: ${SSO_BASE_URI:https://wfeglobalb2cdev.b2clogin.com}             # Such as: https://xxxxb2c.b2clogin.com
          user-flows: # is this really needed?, we're not signing directly into this service. This is a resource. Test removing this.
            sign-up-or-sign-in: ${SIGN_UP_OR_SIGN_IN_USER_FLOW_NAME:B2C_1_phone_based_sign_in_and_sign_up}

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      springframework:
        security: DEBUG
